# Generated by Django 6.0.1 on 2026-02-08 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('poster', models.URLField(help_text='Primary poster image URL')),
                ('backdrop', models.URLField(blank=True, help_text='Wide hero image URL', null=True)),
                ('trailer_url', models.URLField(blank=True, help_text='Link to YouTube/Vimeo trailer', null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='series', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(blank=True, help_text="e.g. 'The Beginning' or leave blank", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Summary for this specific season')),
                ('poster', models.URLField(blank=True, help_text='Per-season poster image', null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.series')),
            ],
            options={
                'ordering': ['season_number'],
                'unique_together': {('series', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('plot', models.TextField(blank=True, help_text='Narrative summary of the episode')),
                ('thumbnail', models.URLField(blank=True, help_text='Preview image for the episode', null=True)),
                ('source_type', models.CharField(choices=[('upload', 'Uploaded File'), ('external', 'External Link')], default='upload', max_length=20)),
                ('video_file', models.FileField(blank=True, help_text='Upload raw MP4 file here', null=True, upload_to='videos/episodes/')),
                ('external_url', models.URLField(blank=True, help_text='Link to external stream if source_type is External', null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, help_text='In minutes', null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='series.season')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
    ]
