# Generated by Django 6.0.1 on 2026-02-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tmdb_id',
            field=models.IntegerField(blank=True, help_text='TMDB ID for metadata sync', null=True),
        ),
    ]
