# Generated by Django 5.2.4 on 2026-02-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_alter_episode_id_alter_episodevideo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='description',
        ),
        migrations.AddField(
            model_name='episode',
            name='plot',
            field=models.TextField(blank=True, help_text='Narrative summary of the episode'),
        ),
        migrations.AddField(
            model_name='episode',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Preview image for the episode', null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, help_text='Summary for this specific season'),
        ),
        migrations.AddField(
            model_name='season',
            name='poster',
            field=models.URLField(blank=True, help_text='Per-season poster image', null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='backdrop',
            field=models.URLField(blank=True, help_text='Wide hero image URL', null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Link to YouTube/Vimeo trailer', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, help_text='In minutes', null=True),
        ),
        migrations.AlterField(
            model_name='episodevideo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.CharField(blank=True, help_text="e.g. 'The Beginning' or leave blank", max_length=255),
        ),
        migrations.AlterField(
            model_name='series',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.URLField(help_text='Primary poster image URL'),
        ),
    ]
