# Generated by Django 6.0.1 on 2026-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_tmdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='backdrop',
        ),
        migrations.AlterField(
            model_name='episode',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Preview image for the episode', null=True, upload_to='thumbnails/episodes/'),
        ),
        migrations.AlterField(
            model_name='season',
            name='poster',
            field=models.ImageField(blank=True, help_text='Per-season poster image', null=True, upload_to='posters/seasons/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.ImageField(help_text='Recommended size: 600x900px (2:3 aspect ratio)', upload_to='posters/series/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='rating',
            field=models.FloatField(blank=True, help_text='Scale: 0.0 to 10.0', null=True),
        ),
    ]
