# Generated by Django 6.0.3 on 2026-05-20 13:06

from django.db import migrations


def publish_existing_series_content(apps, schema_editor):
    Series = apps.get_model("series", "Series")
    Season = apps.get_model("series", "Season")
    Episode = apps.get_model("series", "Episode")

    Series.objects.filter(status="draft").update(status="published")
    Season.objects.filter(status="draft").update(status="published")
    Episode.objects.filter(status="draft").update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_episode_published_at_episode_reviewed_by_and_more'),
    ]

    operations = [
        migrations.RunPython(publish_existing_series_content, migrations.RunPython.noop),
    ]
