# Generated by Django 6.0.3 on 2026-05-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_publish_existing_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSeries',
            fields=[
            ],
            options={
                'verbose_name': 'Draft series',
                'verbose_name_plural': 'Draft series',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('series.series',),
        ),
        migrations.CreateModel(
            name='PendingReviewSeries',
            fields=[
            ],
            options={
                'verbose_name': 'Series pending review',
                'verbose_name_plural': 'Series pending review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('series.series',),
        ),
        migrations.CreateModel(
            name='PublishedSeries',
            fields=[
            ],
            options={
                'verbose_name': 'Published series',
                'verbose_name_plural': 'Published series',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('series.series',),
        ),
    ]
