# Generated by Django 6.0.3 on 2026-06-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_episode_uploaded_by_season_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1920x1080px or wider cinematic 16:9 artwork', null=True, upload_to='heroes/series/'),
        ),
    ]
