# Generated by Django 5.2.4 on 2026-01-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('upload', 'Uploaded File'), ('external', 'External Link')], max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('label', models.CharField(blank=True, help_text='e.g. 1080p, Download Mirror 1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
