# Generated by Django 6.0.1 on 2026-01-30 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_videosource_id'),
        ('movies', '0002_alter_movie_id_alter_movievideo_id'),
        ('series', '0002_alter_episode_id_alter_episodevideo_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosource',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='videosource',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_sources', to='series.episode'),
        ),
        migrations.AddField(
            model_name='videosource',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_sources', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='label',
            field=models.CharField(blank=True, help_text='e.g. 1080p, 720p, Download Mirror 1', max_length=100),
        ),
    ]
