# Generated by Django 6.0.1 on 2026-02-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('poster', models.URLField(help_text='Poster image URL')),
                ('backdrop', models.URLField(blank=True, help_text='Wide hero image URL', null=True)),
                ('source_type', models.CharField(choices=[('upload', 'Uploaded File'), ('external', 'External Link')], default='upload', max_length=20)),
                ('video_file', models.FileField(blank=True, help_text='Upload raw MP4 file here', null=True, upload_to='videos/movies/')),
                ('external_url', models.URLField(blank=True, help_text='Link to external stream if source_type is External', null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='movies', to='categories.category')),
            ],
        ),
    ]
