# Generated by Django 6.0.1 on 2026-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_tmdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backdrop',
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(help_text='Recommended size: 600x900px (2:3 aspect ratio)', upload_to='posters/movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, help_text='Scale: 0.0 to 10.0', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
