# Generated by Django 6.0.3 on 2026-05-20 13:06

from django.db import migrations


def publish_existing_movies(apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")
    Movie.objects.filter(status="draft").update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_published_at_movie_reviewed_by_movie_status_and_more'),
    ]

    operations = [
        migrations.RunPython(publish_existing_movies, migrations.RunPython.noop),
    ]
