# Generated by Django 6.0.3 on 2026-05-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_publish_existing_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftMovie',
            fields=[
            ],
            options={
                'verbose_name': 'Draft Movie',
                'verbose_name_plural': 'Draft Movies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movies.movie',),
        ),
        migrations.CreateModel(
            name='PendingReviewMovie',
            fields=[
            ],
            options={
                'verbose_name': 'Movie Pending Review',
                'verbose_name_plural': 'Movies Pending Review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movies.movie',),
        ),
        migrations.CreateModel(
            name='PublishedMovie',
            fields=[
            ],
            options={
                'verbose_name': 'Published Movie',
                'verbose_name_plural': 'Published Movies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movies.movie',),
        ),
    ]
