# Generated by Django 5.1.5 on 2026-09-26 00:42

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, help_text='Optional fallback. Prefer an external download/source link to reduce storage costs.', null=True, storage=apps.common.storage.LocalVideoStorage(), upload_to='videos/movies/'),
        ),
    ]
