# Generated by Django 5.1.5 on 2026-09-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bunny_available_resolutions',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='movie',
            name='bunny_encode_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='bunny_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='movie',
            name='bunny_video_id',
            field=models.UUIDField(blank=True, editable=False, help_text='Bunny Stream video ID managed by the secure upload panel.', null=True, unique=True),
        ),
    ]
