# Generated by Django 5.1.5 on 2026-09-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_bunny_available_resolutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='bunny_video_id',
            field=models.UUIDField(blank=True, help_text='Paste a Bunny Stream video GUID here, or use the upload panel below to upload directly.', null=True, unique=True),
        ),
    ]
